name: Schedule
on:
  
  schedule:
    - cron: '55 13 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Running
      run: |
        echo "Running!"
     